apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.global.letsencrypt_email }}       # Dynamically fetch email from bootstrap.yaml
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          cloudDNS:
            project: {{ .Values.global.project_id }}     # Fetch project ID dynamically
            hostedZoneName: {{ .Values.global.hostedzone_name }}  # Fetch hosted zone name dynamically
